
steps:
  - task: DeleteFiles@1
    displayName: 'removing dist files'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/dist/'
      Contents: '**/*'
      RemoveDotFiles: true

  - task: NodeTool@0
    displayName: 'using Node 20'
    inputs:
      versionSource: 'spec'
      versionSpec: '20'
      checkLatest: true

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)'

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'run build'

  - task: Npm@1
    displayName: 'npm versioning'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'version patch --no-git-tag-version'

  - bash: |
      npx tfx-cli extension publish \
        --publisher JonasBBernardi \
        --manifest-js './extension.config.js' \
        --token $AZDO_PERSONAL_ACCESS_TOKEN \
        --no-wait-validation
    displayName: 'create extension'